Add more Examples
roc-lang/examples pull request #10
Opened 2023-04-11 11:36 UTC by lukewilliamboswell

This PR adds a number of new examples.

For popular problems updated references to refer to Wikipedia problem description.

2023-04-11 18:02 UTC, Anton-4 commented
Thanks @lukewilliamboswell! I've partly reviewed this and will continue tomorrow.

2023-04-12 10:02 UTC, Anton-4 commented on examples/AplusB/main.roc
I think the chance is small that someone will look for an a + b example but we do demonstrate using args and writing to stout here. What do you think of making this a minimal advent of code template? We could also add search tags like project euler, programming contest, hackerrank...

2023-04-12 10:27 UTC, Anton-4 requested changes

2023-04-12 10:27 UTC, Anton-4 commented on examples/Arithmetic/main.roc
> +            _ -> Task.fail InvalidNumStr
The `readArgs` function adds a lot of noise to a code example. I think we should stick to using expect all the time, except for examples like  "command line args", "advent of code", ...

2023-04-12 10:27 UTC, Anton-4 commented on examples/Arithmetic/main.roc
> +            |> List.map calculate
I think we should split out the vital part of the solution into a separate function. Readers are likely to just want to copy that function.

2023-04-12 10:27 UTC, Anton-4 commented on examples/Arithmetic/main.roc
> +            "\(operation): \(resultStr)"
Given that this function does no calculation, we should probably call it something else :p

2023-04-12 10:27 UTC, Anton-4 commented on examples/TowersOfHanoi/main.roc
> +            _ -> Task.fail InvalidNumStr
I would again remove the `readArgs` here, like mentioned earlier.

2023-04-14 09:40 UTC, lukewilliamboswell commented on examples/AplusB/main.roc
Ok, killed A+B and made it a HelloWorld instead

2023-04-14 09:46 UTC, lukewilliamboswell commented
Thank you for the feedback @Anton-4. I agree we can keep them smaller and use `interface` modules to keep it simple. However, I would like to leave those examples as is, and pull them apart in a follow up PR. I would also like to get some kind of Tags or Search feature in, or at least think about the design, as these examples are going to grow wild pretty quickly if we have too many in just a big list.

2023-04-14 11:45 UTC, Anton-4 approved these changes
Sounds good! I like the diverse set of examples for pattern matching :)

2023-04-14 11:45 UTC, merged