Add RandomNumbers example
roc-lang/examples pull request #20
Opened 2023-04-18 09:57 UTC by lukewilliamboswell

This PR adds an example program that generates and prints random numbers using a URL package of the [JanCVanB/roc-random](https://github.com/JanCVanB/roc-random) and the basic-cli platform.

<img width="949" alt="Screen Shot 2023-04-18 at 19 51 25" src="https://user-images.githubusercontent.com/2679227/232741870-b02b2a53-9de2-4b04-a2b0-b6e67f644715.png">

2023-04-18 11:58 UTC, Anton-4 requested changes
Thanks @lukewilliamboswell! This example will be a big help to a lot of roc users :)

2023-04-18 11:58 UTC, Anton-4 commented on examples/RandomNumbers/main.roc
> +            { seed, numbers }
I'd put this in a separate function, for easy copying and so that it's easy to see immediately what the important part is.

2023-04-18 11:58 UTC, Anton-4 commented on examples/RandomNumbers/main.roc
> +    u16 = Random.u16 25 75
What do you think about using `Random.seed` and `Random.int` here? People can still see the I32 in the return type of the separate function (see next comment).

2023-04-21 09:47 UTC, lukewilliamboswell commented on examples/RandomNumbers/README.md
> +This is example uses the [JanCVanB/roc-random](https://github.com/JanCVanB/roc-random) package and Roc's [basic-cli platform](https://github.com/roc-lang/basic-cli) to generate a list of random numbe
Added a couple of paragraphs to explain these concepts for newcomers.

2023-04-21 10:42 UTC, Anton-4 approved these changes
Thanks @lukewilliamboswell, looks good!

2023-04-21 10:42 UTC, merged