Upgrade examples to Purity Inference
roc-lang/examples pull request #223
Opened 2024-12-20 04:55 UTC by lukewilliamboswell

2024-12-28 18:23 UTC, Anton-4 commented
fyi I added "DO NOT MERGE" so this is held until the basic-cli pre-release becomes a full release

2024-12-28 18:59 UTC, Anton-4 requested changes
I can take some of these as well, whoever gets to it first

2024-12-28 18:59 UTC, Anton-4 commented on examples/RandomNumbers/main.roc
> -# This is NOT cryptograhpically secure!
Seems like we should keep this :smile:

2024-12-28 18:59 UTC, Anton-4 commented on examples/TaskLoop/main.roc
> -    sum = Task.loop! 0 addNumberFromStdin
We should rename this example :smile:

2024-12-28 18:59 UTC, Anton-4 commented on examples/Tasks/main.roc
Need to rename this one as well. The README for this example also needs to be updated.

2024-12-28 22:11 UTC, lukewilliamboswell commented on examples/DesugaringTry/main.roc
> +main! = \_ ->
Agree... I just never came back to these and made the changes here yet.

2025-01-03 14:42 UTC, Anton-4 commented
I'm going to take care of my feedback

2025-01-03 15:49 UTC, Anton-4 approved these changes

2025-01-03 15:50 UTC, Anton-4 commented
This can be merged once basic-cli 0.18.0 is out of pre-release.

2025-01-04 21:11 UTC, merged